"""Additional user journeys shared by real-browser and isolated-renderer tests."""
def run_extra(page,check,input_,action,go,accept,root,memory):
    page.set_viewport_size({'width':390,'height':844})
    go(page,'client')
    input_(page,'client.name','QA Client عربي')
    page.locator('#main summary').first.click()
    input_(page,'client.notesClient','ملاحظات العميل — Reference QA-001')
    go(page,'gold');page.locator('[data-action=gold-tab][data-tab=entry]').click()
    input_(page,'gold.draft.quantity','0.25');action(page,'clear-gold');accept(page)
    check('clear gold inputs retains saved batches',page.locator('[data-field="gold.draft.quantity"]').input_value()=='' and '2' in page.locator('[data-action=gold-tab][data-tab=records]').inner_text())
    go(page,'portfolio');page.locator('[data-action=holding-tab][data-tab=entry]').click()
    action(page,'clear-holding');accept(page)
    check('clear holding inputs retains saved holdings',page.locator('[data-field="holdingDraft.name"]').input_value()=='' and '1' in page.locator('[data-action=holding-tab][data-tab=records]').inner_text())
    page.locator('[data-action=holding-tab][data-tab=records]').click();action(page,'delete-holding');page.locator('#confirmCancel').click()
    check('cancel holding deletion preserves record',page.locator('.record-card:visible').count()==1)
    page.locator('#toolsButton').click();page.locator('[data-screen=profile]').click()
    page.locator('#main summary').click();page.locator('#signatureUpload').set_input_files(root/'dist/icon192.png')
    page.wait_for_selector('.image-preview',state='attached')
    check('signature image accepted',page.locator('.image-preview').count()==1)
    page.locator('#main summary').click();action(page,'remove-signature')
    check('signature removal applied',page.locator('.image-preview').count()==0)
    go(page,'reports');page.locator('#autoMaster').check()
    check('auto master switch on',page.locator('#autoMaster').is_checked());page.locator('#autoMaster').uncheck()
    go(page,'client');action(page,'new-client');accept(page)
    page.wait_for_function("document.querySelector('[data-field=\"client.name\"]').value === ''")
    check('new client starts without inherited positions',page.locator('[data-field="client.name"]').input_value()=='')
    input_(page,'client.name','QA Second Client');action(page,'records')
    page.locator('.record-card',has_text='QA Client عربي').locator('[data-action=open-record]').click()
    page.wait_for_function("document.querySelector('#clientContext').textContent.includes('QA Client عربي')")
    check('record selector restores correct client',page.locator('[data-field="client.name"]').input_value()=='QA Client عربي')
    go(page,'gold');page.locator('[data-action=gold-tab][data-tab=records]').click()
    check('new client does not delete previous gold positions',page.locator('.record-card:visible').count()==2)
    check('HTML element identifiers are unique',page.evaluate("(()=>{const a=[...document.querySelectorAll('[id]')].map(x=>x.id);return new Set(a).size===a.length})()"))
    page.locator('[data-action=gold-tab][data-tab=entry]').click();input_(page,'gold.draft.quantity','-1');action(page,'add-gold')
    check('invalid batch is rejected visibly',bool(page.locator('#goldError').inner_text()))
    page.locator('[data-action=gold-tab][data-tab=records]').click()
    check('invalid batch does not change saved rows',page.locator('.record-card:visible').count()==2)
    page.locator('summary:visible').click();action(page,'clear-batches');page.locator('#confirmCancel').click()
    check('cancel clear-all preserves batches',page.locator('.record-card:visible').count()==2)
    go(page,'client')
